name: fridge_to_fork_assistant
description: A new Flutter project.
publish_to: "none"

# Bạn có thể chọn version nào cũng được, thường để 1.0.0 cho bản đầu tiên
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
 
  flutter:
    sdk: flutter
    

  # Giữ lại icon mặc định
  cupertino_icons: ^1.0.8
  dotted_border: ^3.1.0
  # Lấy bản mới hơn
  google_fonts: ^6.3.3
  table_calendar: ^3.0.9
  # Giữ lại thư viện quét mã từ nhánh manh
  mobile_scanner: ^7.1.4
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  http: ^1.6.0
  go_router: ^17.0.1
  cloud_firestore: ^6.1.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  flutter_dotenv: ^6.0.0
  google_generative_ai: ^0.4.7
  flutter_localization: ^0.3.3
  flutter_local_notifications: ^19.5.0
  flutter_timezone: ^5.0.1
  timezone: ^0.10.1
  firebase_messaging: ^16.1.0
  barcode_widget: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - .env